apps/registro_hora/urls.py
from django.urls import path


from apps.registro_hora import views

app_name='registro_hora'

urlpatterns = [
    path('create/<int:id>', views.create, name='create'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('list/<int:id>', views.list, name='list'),
]

gestao_rh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('horas/', include('apps.registro_hora.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/registro_hora/models.py
from django.db import models

from apps.funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(
        max_length=255)
    funcionario = models.ForeignKey(
        Funcionario, on_delete=models.SET_NULL, null=True, blank=True)
    horas = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self) -> str:
        return f'{self.motivo}'

apps/registro_hora/forms.py
from django import forms

from .models import RegistroHoraExtra


class RegistroHoraExtraForm(forms.ModelForm):

    class Meta:
        model = RegistroHoraExtra
        exclude = ('funcionario',)

apps/registro_hora/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from apps.funcionarios.models import Funcionario

from .forms import RegistroHoraExtraForm
from .models import RegistroHoraExtra


def list(request, id):
    context = {}
    horas = RegistroHoraExtra.objects.filter(funcionario_id=id)
    funcionario = Funcionario.objects.get(id=id)
    context['funcionario'] = funcionario
    if horas:
        context['horas'] = horas
        
    else:
        context['sem_horas'] = True
    
    return render(request, 'list_horas.html', context)
        


def create(request, id):
    if request.method == 'POST':
        form = RegistroHoraExtraForm(request.POST)
        if form.is_valid():
            hora = RegistroHoraExtra.objects.create(
                motivo=form.cleaned_data['motivo'],
                horas=form.cleaned_data['horas'],
            )
            hora.funcionario_id = id
            hora.save()

            return redirect(reverse('funcionario:list'))
        else:
            return redirect(reverse('funcionario:list'))
    
    context = {
        'form': RegistroHoraExtraForm
    }
    return render(request, 'create_horas.html', context)


@csrf_exempt
def delete(request):
    if request.method == 'POST':
        id_hora = request.POST['id_hora']
        try: 
            RegistroHoraExtra.objects.get(id=id_hora).delete()
            response = {'icon': 'success', 'title': 'Sucesso', 'text': 'Funcionário removido com sucesso!'}
        except Funcionario.DoesNotExist:
            response = {'icon': 'error', 'title': 'Erro', 'text': 'Não foi encontrado o funcionário'}

        return JsonResponse(response, safe=False)

def edit(request, id):
    if request.method == 'POST':
        form = RegistroHoraExtraForm(request.POST)
        if form.is_valid():
            horas = RegistroHoraExtra.objects.get(id=id)
            horas.horas = form.cleaned_data['horas']
            horas.motivo = form.cleaned_data['motivo']
            horas.save()

            return redirect(reverse('funcionario:list'))

    context = {
        'form': RegistroHoraExtraForm()
    }

    return render(request, 'edit_horas.html', context)

apps/registro_hora/templates/create_horas.html
{% extends 'base.html' %}

{% block title %} Cadastrar Hora {% endblock title %}
{% block navbar %} {% include 'partials/navbar.html' %} {% endblock  %}

{% block main %}
    <h1 class="text-center mt-5">Formulário: Cadastrar Hora</h1>

<div class="d-flex justify-content-center mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-dark">Cadastrar Hora</button>
    </form>
</div>


{% endblock main %}

apps/registro_hora/templates/edit_horas.html
{% extends 'base.html' %}

{% block title %} Editar Horas {% endblock title %}
{% block navbar %} {% include 'partials/navbar.html' %} {% endblock  %}

{% block main %}
    <h1 class="text-center mt-5">Formulário: Editar horas</h1>

<div class="d-flex justify-content-center mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-dark">Editar hora</button>
    </form>
</div>


{% endblock main %}

apps/registro_hora/templates/list_horas.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Lista de Horas {% endblock title %}
{% block navbar %} {% include 'partials/navbar.html' %} {% endblock  %}

{% block main %}
<div class="card mt-5 ">
  <div class="card-header">
    <div class="d-flex bd-highlight">
        <div class="p-2 w-100  text-center">Horas do funcionario: {{funcionario.first_name}}</div>
        <div class="p-2 flex-shrink-1 bd-highlight">
            <a href="{% url 'registro_hora:create' funcionario.id %}" class="btn btn-outline-dark">
                <span class="material-icons">schedule</span>
            </a>
        </div>
    </div>
  </div>
  <div class="card-body">
    
    {% if sem_horas %}
        <div class="alert alert-warning" role="alert">
            <h4 class="alert-heading">Ops...</h4>
            <p>Esse funcionário ainda não possui horas cadastradas</p>
            <hr>
            <p class="mb-0">Cadastre horas para esse usuário!</p>
        </div>
    {% else %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Motivo</th>
                    <th scope="col">Horas</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
            {% for hora in horas  %}
                <tr>
                    <th scope="row">{{ hora.id }}</th>
                    <td scope="">{{ hora.motivo }}</td>
                    <td scope="">{{ hora.horas }}</td>
                    <td scope="">
                        <a href="{% url 'registro_hora:edit' hora.id %}" class="btn btn-outline-dark">
                            <span class="material-icons">edit</span>
                        </a>

                        <button id="{{ hora.id }}" class="btn btn-outline-danger remove_hora">
                            <span class="material-icons">delete</span>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
  </div>
</div>
{% endblock main %}

{% block script %}

    <script src="{% static 'js/apps/horas.js' %}"></script>

{% endblock  %}