apps/core/urls.py
from django.urls import path

from apps.core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('celery', views.send_email),
]

apps/empresas/urls.py
from django.urls import path


from apps.empresas import views

app_name='empresa'

urlpatterns = [
    path('create', views.create, name='create'),
    path('edit/<int:id>', views.edit, name='edit'),
]

apps/funcionarios/urls.py
from django.urls import path


from apps.funcionarios import views

app_name = 'funcionario'

urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('add', views.add, name='add'),
]

gestao_rh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('horas/', include('apps.registro_hora.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required

from .tasks import send_report

@login_required
def home(request):
    data = {}
    data['usuario'] = request.user
    return render(request, 'core/home.html', data)



def send_email(request):
    send_report.delay()
    return HttpResponse('Task add in queue')

apps/core/templates/core/home.html
{% extends 'base.html' %}

{% block title %} Olá {% endblock title %}
{% block navbar %} {% include 'partials/navbar.html' %} {% endblock  %}

{% block main %}

    {% comment %} <div class="row">
        <div class="col-sm">
            One of three columns
        </div>

        <div class="col-sm">
            {{usuario.first_name}}
            <a href="{% url 'funcionario:list' %}">Gerenciar funcionários</a>
        </div>
        
        <div class="col-sm">
            <a href="{% url 'logout' %}">Sair</a>

            
            {% if usuario.empresa %}
                <h2>{{usuario.empresa.nome}}</h2>
                 <a href="{% url 'empresa:edit' usuario.empresa.id %}">Editar Empresa</a>
            {% else %}
                <a href="{% url 'empresa:create' %}">Criar Empresa</a>    
            {% endif %}
                

        </div>
    </div> {% endcomment %}


{% endblock main %}